### PR TITLE
Change K.1.4 CIN2/ungraded HSIL lookback to 2-3 years #69

### PR DESCRIPTION
**Pull request by mrnosal**
Update logic For K.1.4 Heading 4.5 to check for two occurrences of CIN2/ungraded HSIL occur >=24 months and < 3 years of each other.

### CODE REVIEW

**Comment by mickohanlon23** [comment]
Would you mind adding a test or two for this scenario, since this is directly to address an issue with one of the Test Script patients? Something that shows that a patient with two CIN2 results a year apart will not get this recommendation, but that that a patient with CIN2 results two years apart _will_ get this recommendation. Might be helpful to recreate **Test Patient 37** from the Test Scripts spreadsheet, since this was the patient that led to the discovery of this issue.

**Comment by mrnosal** [comment]
Added three test cases: one recreates Test patient 37, one has 2x CIN2 1 year apart (doesn't get recommendation) and one has 2x CIN2 two years apart (gets this recommendation).

**Review by mickohanlon23 — APPROVED** [review]
Great! The test case for patient 37 shows that the recommendation we're giving now aligns with what is expected by the doctors! And the test case with 2 CIN2 results between 2-3 years apart is successfully giving _this_ recommendation. Thanks for adding the tests!

**Comment by mickohanlon23** [comment]
Resolves issue #69

**Pull request merged**
